project:
  type: website
  output-dir: docs
  
author: "RP Wadhwa"
website:
  title: "Data Visualisation Portfolio"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Homepage
      - href: task3.qmd
        text: Complex Graphics
      - href: task4.qmd
        text: Animation  
      - href: dash.qmd
        text: Dashboard
      
format:
  html:
    theme: cosmo
    toc: true
    code-fold: true
    number-sections: true

execute:
  echo: true
  warning: false
  message: false
